# Generated by Django 4.2.2 on 2023-06-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('folio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=30)),
                ('fecha_ingreso_sistema', models.DateField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
    ]
